### ISSUE TITLE
Match React’s Object.assign dependency to reduce bundle impact

### ISSUE THREAD

**Issue by jaydenseric** [airbnb/prop-types-exact#6]
As this package is intended to be paired with React it makes sense to [use here](https://github.com/airbnb/prop-types-exact/blob/v1.1.2/.babelrc#L4) the same Object.assign implementation ([`object-assign`](https://www.npmjs.com/package/object-assign)) [they use](https://github.com/facebook/react/blob/v16.3.1/packages/react-dom/package.json#L18) to reduce duplication in bundles.

Doing this will reduce the page load of a Next.js hello world app by 661 B (min gzip):

<img width="288" alt="screen shot 2018-04-10 at 3 11 49 pm" src="https://user-images.githubusercontent.com/1754873/38537380-afd9077c-3cd1-11e8-9b9a-0ea51149430d.png">

**Comment by lencioni** [comment]
Good find! Thanks for opening this issue and caring about performance. 🥇 

I agree that it would be ideal if these were using the same library. However, I'm not really aware of what the differences are, why there seem to be two packages that seem to do similar things, and which one we should settle on. My hunch is that perhaps the maintainers of object-assign and object.assign should get together and deprecate one of the two packages and encourage everyone to move over to the other. object.assign claims spec compliance, so that seems like a good choice to me. Are there any advantages to object-assign?

@ljharb @sindresorhus any thoughts?

**Comment by ljharb** [comment]
I'm pretty insistent on retaining `object.assign` in this package, since that's what we use in airbnb-browser-shims, and in all of our open source packages.

A better path imo would be trying to get React to switch its dependency.

In the meantime, you can certainly alias one for the other in your bundles.

**Comment by jaydenseric** [comment]
It does not matter where else Airbnb uses `object.assign`, changing the dependency here won't affect the other projects and but it will solve a real problem for almost every `prop-types-exact` user, who may not even be aware of the problem.

If React changes their implementation (unlikely?), then it makes sense to change it again here to match.

All you have to do is delete the custom config for `babel-plugin-transform-replace-object-assign` [here](https://github.com/airbnb/prop-types-exact/blob/v1.1.2/.babelrc#L4) and let it use the default, `object-assign` ([default since I rewrote the plugin for Babel v7](https://github.com/newoga/babel-plugin-transform-replace-object-assign/pull/3)).

**Comment by ljharb** [comment]
It's an unfortunate default, since `object.assign` is a better choice overall (and predates the hyphenated one). Is aliasing one to the other in your webpack config not a palatable option?
